### ISSUE TITLE
A bug of evaluating selfplay

### ISSUE THREAD

**Issue by HMJiangGatech** [google/airdialogue#10]
https://github.com/google/airdialogue/blob/604f34dcaca6561dde816822b68d6e990b73d076/airdialogue/evaluator/evaluator_main.py#L244-L247

It doesn't make sense if `pred_json_obj` already has `action` and use `unk`.

Switch line 245 & line 247 ?

**Comment by josephch405** [comment]
Will be fixed in #8 by inverting the predicate
