### ISSUE TITLE
Bugs in the function `score_human_data` in evaluator/evaluator_main.py

### ISSUE THREAD

**Issue by HMJiangGatech** [google/airdialogue#11]
1.
In https://github.com/google/airdialogue/blob/604f34dcaca6561dde816822b68d6e990b73d076/airdialogue/evaluator/evaluator_main.py#L189-L190
It acutally should load `flags.true_kb` and `flags.true_data`.

2. 
In https://github.com/google/airdialogue/blob/604f34dcaca6561dde816822b68d6e990b73d076/airdialogue/evaluator/evaluator_main.py#L191-L192

There is an error about tensorflow (tf v1.15):
AttributeError: module 'tensorflow._api.v1.compat.v1.io.gfile' has no attribute 'Open'
Use `tf.gfile.GFile` as Line 236-238?

**Comment by josephch405** [comment]
Fixed in #8
